import { defineConfig } from 'vite-plus'

export default defineConfig({
  staged: {
    '*': 'vp check --fix',
  },
  fmt: {
    printWidth: 100,
    tabWidth: 2,
    useTabs: false,
    semi: false,
    singleQuote: true,
    quoteProps: 'consistent',
    jsxSingleQuote: false,
    trailingComma: 'es5',
    bracketSpacing: true,
    bracketSameLine: false,
    arrowParens: 'avoid',
    ignorePatterns: ['dist'],
  },
  lint: {
    plugins: ['import', 'promise', 'typescript', 'unicorn', 'oxc'],
    env: {
      browser: true,
      node: true,
      es2021: true,
    },
    categories: {
      correctness: 'error',
    },
    rules: {
      'accessor-pairs': 'error',
      'array-callback-return': 'error',
      'arrow-body-style': 'error',
      'block-scoped-var': 'error',
      'complexity': ['error', 10],
      'curly': 'error',
      'default-case-last': 'error',
      'eqeqeq': 'error',
      'for-direction': 'error',
      'func-names': ['error', 'as-needed'],
      'func-style': [
        'error',
        'declaration',
        {
          allowArrowFunctions: true,
        },
      ],
      'grouped-accessor-pairs': 'error',
      'guard-for-in': 'error',
      'id-length': [
        'error',
        {
          min: 1,
          max: 35,
        },
      ],
      'max-classes-per-file': 'error',
      'max-depth': [
        'error',
        {
          max: 4,
        },
      ],
      'max-nested-callbacks': 'error',
      'max-params': 'error',
      'no-alert': 'error',
      'no-async-promise-executor': 'error',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-constructor-return': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-else-if': 'error',
      'no-duplicate-case': 'error',
      'no-empty': [
        'error',
        {
          allowEmptyCatch: true,
        },
      ],
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-eval': 'error',
      'no-ex-assign': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-global-assign': 'error',
      'no-implicit-coercion': [
        'error',
        {
          allow: ['!!'],
        },
      ],
      'no-inner-declarations': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-lonely-if': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-multi-assign': 'error',
      'no-multi-str': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-new-wrappers': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-object-constructor': 'error',
      'no-param-reassign': [
        'error',
        {
          props: false,
        },
      ],
      'no-promise-executor-return': 'error',
      'no-proto': 'error',
      'no-prototype-builtins': 'error',
      'no-regex-spaces': 'error',
      'no-script-url': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unneeded-ternary': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-useless-backreference': 'error',
      'no-useless-call': 'error',
      'no-useless-catch': 'error',
      'no-useless-computed-key': [
        'error',
        {
          enforceForClassMembers: true,
        },
      ],
      'no-useless-concat': 'error',
      'no-useless-escape': 'error',
      'no-useless-rename': 'error',
      'no-useless-return': 'error',
      'no-var': 'error',
      'no-void': 'error',
      'no-with': 'error',
      'object-shorthand': 'error',
      'prefer-const': 'error',
      'prefer-exponentiation-operator': 'error',
      'prefer-object-spread': 'error',
      'prefer-promise-reject-errors': [
        'error',
        {
          allowEmptyReject: true,
        },
      ],
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'radix': 'error',
      'require-yield': 'error',
      'symbol-description': 'error',
      'use-isnan': 'error',
      'yoda': 'error',
      'import/first': 'error',
      'import/no-absolute-path': 'error',
      'import/no-anonymous-default-export': 'error',
      'import/no-default-export': 'error',
      'import/no-duplicates': 'error',
      'import/no-dynamic-require': 'error',
      'import/no-empty-named-blocks': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-named-as-default': 'error',
      'import/no-named-as-default-member': 'error',
      'import/no-named-default': 'error',
      'import/no-self-import': 'error',
      'import/no-webpack-loader-syntax': 'error',
      'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
      'promise/no-multiple-resolved': 'error',
      'promise/no-nesting': 'error',
      'promise/no-new-statics': 'error',
      'promise/no-return-wrap': 'error',
      'promise/param-names': 'error',
      'promise/valid-params': 'error',
      'unicorn/catch-error-name': 'error',
      'unicorn/consistent-function-scoping': 'error',
      'unicorn/custom-error-definition': 'error',
      'unicorn/error-message': 'error',
      'unicorn/escape-case': 'error',
      'unicorn/explicit-length-check': 'error',
      'unicorn/no-abusive-eslint-disable': 'error',
      'unicorn/no-array-method-this-argument': 'error',
      'unicorn/no-await-expression-member': 'error',
      'unicorn/no-console-spaces': 'error',
      'unicorn/no-document-cookie': 'error',
      'unicorn/no-empty-file': 'error',
      'unicorn/no-hex-escape': 'error',
      'unicorn/no-instanceof-array': 'error',
      'unicorn/no-invalid-remove-event-listener': 'error',
      'unicorn/no-lonely-if': 'error',
      'unicorn/no-negated-condition': 'error',
      'unicorn/no-new-array': 'error',
      'unicorn/no-new-buffer': 'error',
      'unicorn/no-object-as-default-parameter': 'error',
      'unicorn/no-static-only-class': 'error',
      'unicorn/no-thenable': 'error',
      'unicorn/no-this-assignment': 'error',
      'unicorn/no-typeof-undefined': 'error',
      'unicorn/no-unnecessary-await': 'error',
      'unicorn/no-unreadable-iife': 'error',
      'unicorn/no-useless-fallback-in-spread': 'error',
      'unicorn/no-useless-length-check': 'error',
      'unicorn/no-useless-promise-resolve-reject': 'error',
      'unicorn/no-useless-spread': 'error',
      'unicorn/no-useless-switch-case': 'error',
      'unicorn/no-zero-fractions': 'error',
      'unicorn/prefer-add-event-listener': 'error',
      'unicorn/prefer-array-find': 'error',
      'unicorn/prefer-array-flat': 'error',
      'unicorn/prefer-array-flat-map': 'error',
      'unicorn/prefer-array-index-of': 'error',
      'unicorn/prefer-array-some': 'error',
      'unicorn/prefer-blob-reading-methods': 'error',
      'unicorn/prefer-code-point': 'error',
      'unicorn/prefer-date-now': 'error',
      'unicorn/prefer-default-parameters': 'error',
      'unicorn/prefer-dom-node-append': 'error',
      'unicorn/prefer-dom-node-dataset': 'error',
      'unicorn/prefer-dom-node-remove': 'error',
      'unicorn/prefer-dom-node-text-content': 'error',
      'unicorn/prefer-event-target': 'error',
      'unicorn/prefer-includes': 'error',
      'unicorn/prefer-keyboard-event-key': 'error',
      'unicorn/prefer-logical-operator-over-ternary': 'error',
      'unicorn/prefer-math-trunc': 'error',
      'unicorn/prefer-modern-dom-apis': 'error',
      'unicorn/prefer-modern-math-apis': 'error',
      'unicorn/prefer-native-coercion-functions': 'error',
      'unicorn/prefer-negative-index': 'error',
      'unicorn/prefer-number-properties': [
        'error',
        {
          checkInfinity: false,
        },
      ],
      'unicorn/prefer-object-from-entries': 'error',
      'unicorn/prefer-prototype-methods': 'error',
      'unicorn/prefer-query-selector': 'error',
      'unicorn/prefer-regexp-test': 'error',
      'unicorn/prefer-set-has': 'error',
      'unicorn/prefer-set-size': 'error',
      'unicorn/prefer-string-slice': 'error',
      'unicorn/prefer-string-starts-ends-with': 'error',
      'unicorn/prefer-string-trim-start-end': 'error',
      'unicorn/prefer-ternary': ['error', 'only-single-line'],
      'unicorn/prefer-type-error': 'error',
      'unicorn/require-array-join-separator': 'error',
      'unicorn/require-number-to-fixed-digits-argument': 'error',
      'unicorn/switch-case-braces': 'error',
      'unicorn/text-encoding-identifier-case': 'error',
      'unicorn/throw-new-error': 'error',
      'typescript/adjacent-overload-signatures': 'error',
      'typescript/array-type': [
        'error',
        {
          default: 'array-simple',
          readonly: 'generic',
        },
      ],
      'typescript/ban-tslint-comment': 'error',
      'typescript/ban-types': 'error',
      'typescript/class-literal-property-style': 'error',
      'typescript/consistent-generic-constructors': 'error',
      'typescript/consistent-indexed-object-style': 'error',
      'typescript/consistent-type-assertions': 'error',
      'typescript/consistent-type-definitions': 'error',
      'typescript/consistent-type-imports': 'error',
      'typescript/no-confusing-non-null-assertion': 'error',
      'typescript/no-empty-interface': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-extraneous-class': 'error',
      'typescript/no-inferrable-types': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-mixed-enums': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-nullish-coalescing': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-non-null-assertion': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-useless-empty-export': 'error',
      'typescript/no-var-requires': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-for-of': 'error',
      'typescript/prefer-function-type': 'error',
      'typescript/prefer-literal-enum-member': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/prefer-ts-expect-error': 'error',
      'typescript/triple-slash-reference': 'error',
      'typescript/unified-signatures': 'error',
    },
    overrides: [
      {
        files: ['*.config.{ts,js,mjs,cjs}'],
        rules: {
          'import/no-default-export': 'off',
        },
      },
      {
        files: ['**/*.{js,jsx,cjs,mjs}'],
        rules: {
          'class-methods-use-this': 'error',
          'consistent-return': 'error',
          'constructor-super': 'error',
          'default-param-last': 'error',
          'dot-notation': 'error',
          'getter-return': 'error',
          'import/default': 'error',
          'import/named': 'error',
          'import/namespace': 'error',
          'no-array-constructor': 'error',
          'no-const-assign': 'error',
          'no-dupe-class-members': 'error',
          'no-dupe-keys': 'error',
          'no-duplicate-imports': 'error',
          'no-empty-function': [
            'error',
            {
              allow: ['arrowFunctions'],
            },
          ],
          'no-func-assign': 'error',
          'no-implied-eval': 'error',
          'no-import-assign': 'error',
          'no-loop-func': 'error',
          'no-obj-calls': 'error',
          'no-redeclare': 'error',
          'no-setter-return': 'error',
          'no-shadow': [
            'error',
            {
              builtinGlobals: false,
              hoist: 'functions',
              ignoreOnInitialization: true,
            },
          ],
          'no-this-before-super': 'error',
          'no-throw-literal': 'error',
          'no-undef': 'error',
          'no-unreachable': 'error',
          'no-unsafe-negation': 'error',
          'no-unused-expressions': 'error',
          'no-unused-vars': 'error',
          'no-use-before-define': 'error',
          'no-useless-constructor': 'error',
          'prefer-rest-params': 'error',
          'promise/no-return-in-finally': 'error',
          'require-await': 'error',
          'unicorn/no-useless-undefined': 'error',
          'valid-typeof': 'error',
        },
      },
      {
        files: ['**/*.{ts,tsx}'],
        rules: {
          'typescript/no-array-constructor': 'error',
          'typescript/no-dupe-class-members': 'error',
          'typescript/no-empty-function': [
            'error',
            {
              allow: ['arrowFunctions'],
            },
          ],
          'typescript/no-loop-func': 'error',
          'typescript/no-loss-of-precision': 'error',
          'typescript/no-redeclare': 'error',
          'typescript/no-shadow': [
            'error',
            {
              builtinGlobals: false,
              hoist: 'functions',
            },
          ],
          'typescript/no-unused-expressions': 'error',
          'typescript/no-useless-constructor': 'error',
          'typescript/default-param-last': 'error',
          'typescript/no-invalid-void-type': 'error',
        },
      },
    ],
    ignorePatterns: ['dist', 'vite.config.ts', '.docs'],
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
  pack: {
    entry: ['src/index.ts'],
    dts: true,
    format: ['esm', 'cjs'],
  },
})
